### PR TITLE
fix: move refresh token from localStorage to httpOnly cookie

### LINKED ISSUE #4: Move refresh token from localStorage to httpOnly cookie
## Problem

The full auth session (including refresh token) is stored in `localStorage` via Zustand persist middleware:

```ts
// frontend/src/stores/auth-store.ts
persist(
  (set) => ({ ... }),
  { name: "kantor-auth", partialize: (state) => ({ session: state.session }) },
)
```

`localStorage` is accessible to any JavaScript on the page. If an XSS vulnerability exists, an attacker can exfiltrate the refresh token and maintain long-term access (up to 7 days).

## Expected Behavior

- Refresh tokens should be stored in an **httpOnly, Secure, SameSite=Strict** cookie set by the backend
- The frontend should not have JavaScript access to the refresh token
- Access tokens can remain in memory (short-lived, 15 min)

## Impact

- Refresh token theft via XSS grants 7-day persistent access
- Even after the user logs out in the browser, a stolen refresh token remains valid

## Files

- `frontend/src/stores/auth-store.ts` (lines 12-26)
- `frontend/src/services/auth.ts` (refresh logic)
- `backend/internal/handler/auth/handler.go` (token issuance — set cookie here)
- `backend/internal/app/app.go` (CORS config — `AllowCredentials: true` already set)

### PR DESCRIPTION
**Pull request by mensafri**
## Summary
- Refresh token no longer returned in JSON response body (`json:"-"` tag on `TokenPair.RefreshToken`)
- Backend sets `httpOnly, Secure, SameSite=Strict` cookie on login/register/refresh, scoped to `/api/v1/auth`
- Backend reads refresh token from cookie on refresh/logout endpoints, clears cookie on logout
- Frontend API client sends `credentials: "include"` so cookies are sent automatically
- Frontend auth service no longer sends refresh_token in request bodies
- Removed `refresh_token` from frontend `AuthTokens` type

Closes #4

### CODE REVIEW

File: frontend/src/lib/api-client.ts [hunk 1]
```diff
@@ -53,6 +53,7 @@ export async function requestEnvelope<TData>(
   const response = await fetch(`${API_BASE_URL}${path}`, {
     ...init,
     headers,
+    credentials: "include",
```
Comment (KeyCode17) [inline frontend/src/lib/api-client.ts]: **`credentials: "include"` is set globally on ALL requests** (Medium)

This means every API call (not just auth) sends cookies cross-origin. While the refresh token cookie is scoped to `/api/v1/auth` path and won't be included in non-auth requests by the browser, setting `credentials: "include"` globally has side-effects:

1. Browsers enforce stricter CORS preflight rules for credentialed requests (no wildcard `Access-Control-Allow-Origin`)
2. Every request becomes a "credentialed" fetch, even when not needed

Since the cookie `Path` is `/api/v1/auth`, the cookie is only sent on auth routes anyway. This is fine functionally, but consider documenting why it's set globally — or scope it only to auth calls if you want to be precise.

File: frontend/src/services/auth.ts [hunk 2]
```diff
@@ -79,13 +68,8 @@ export async function ensureAuthenticated(): Promise<AuthSession | null> {
...
-  if (!session.tokens.refresh_token) {
-    store.clearSession();
-    return null;
-  }
-
   try {
-    const refreshedSession = await refresh(session.tokens.refresh_token);
+    const refreshedSession = await refresh();
     store.setSession(refreshedSession);
     return refreshedSession;
```
Comment (KeyCode17) [inline frontend/src/services/auth.ts]: **Good simplification** — since the refresh token is no longer accessible to JS, the check for `!session.tokens.refresh_token` is correctly removed. The browser handles cookie presence transparently.

The only edge case: if the cookie expires (7 days) but the access token metadata still exists in localStorage, `ensureAuthenticated` will try to refresh, get a 401, clear session, and redirect to login. This is the correct behavior.

File: backend/internal/dto/auth.go [hunk 3]
```diff
@@ -21,7 +21,7 @@ type LogoutRequest struct {
 
 type TokenPair struct {
 	AccessToken  string `json:"access_token"`
-	RefreshToken string `json:"refresh_token"`
+	RefreshToken string `json:"-"`
```
Comment (KeyCode17) [inline backend/internal/dto/auth.go]: **`json:"-"` is the right approach** — the refresh token is still in the struct for internal use but never serialized to the client. Clean.

File: backend/internal/handler/auth/handler.go [hunk 4]
```diff
@@ -5,25 +5,35 @@ import (
...
 
+	"github.com/kana-consultant/kantor/backend/internal/config"
 	"github.com/kana-consultant/kantor/backend/internal/dto"
 	platformmiddleware "github.com/kana-consultant/kantor/backend/internal/middleware"
 	"github.com/kana-consultant/kantor/backend/internal/response"
 	authservice "github.com/kana-consultant/kantor/backend/internal/service/auth"
 )
 
+const refreshTokenCookie = "refresh_token"
+
```
[the remark this answers is not in the document]
Comment (mensafri) [reply backend/internal/handler/auth/handler.go]: Done ✅ Changed to `SameSiteLaxMode`. Agree that Strict would break sessions from external redirects (email/Slack links), and Lax is still safe against CSRF since `/auth/refresh` is a JS-initiated POST, not a navigation.
